### ISSUE TITLE
feat(api): count more than 10k with es

### ISSUE THREAD

**Issue by rap2hpoutre** [betagouv/service-national-universel#1047]
According to @goffle on peut sur clevercloud avoir le vrai chiffre (plus que 10000) en total. C'est cool, il faut qu'on mette ça par défaut dans nos requêtes ES:

```
GET index/_search
{
    "size":1,
    "track_total_hits": true
}
```

**Comment by tangimds** [comment]
@lucienklein tu peux essayer si tu veux ,mais n'y passe pas trop de temps non plus ! ~30-45 min
