### ISSUE TITLE
feat: statut contrat par jeune

### ISSUE THREAD

**Issue by tangimds** [betagouv/service-national-universel#1157]
### Fonctionnalité liée à un problème ?

- depuis le tableau de bord lorsque l'on clique sur Statut Contrat > Validée OU Statut Contrat > Envoyée , le profil du volontaire apparait aux 2 endroits alors qu'il n'a qu'1 seul contrat et qu'il est envoyé .
- Explication vidéo :[https://www.loom.com/share/36ceee2c3b9845278ddfb7e525368afc](https://www.loom.com/share/36ceee2c3b9845278ddfb7e525368afc)

### Fonctionnalité

> **Solution(s) envisagée(s)**
> Supprimer tous contrats après changement du statut de la candidature :
> Statut de départ : Validée
> Statut d'arrivée :
> 
> - En attente de validation
> - En attente de vérification de l'éligibilité
> - Refusée
> - Annulée
> - En attente d'acceptation
> 
> ⚠️ conserver le contrat si le statut d'arrivée est :
> 
> - Abandonnée
> - Effectuée
> - En cours

Je pense qu'il ne faut pas supprimer les contrats.
On peut échanger pour expliquer l'existant et voir comment on peut améliorer ca !

### autre ticket lié
Depuis l'onglet volontaire , lorsque je filtre selon le statut de mission = en attente de validation ; département : Réunion : cohorte : 2020

Je tombe sur 10 volontaires concernés : [https://admin.snu.gouv.fr/volontaire?DEPARTMENT=["La+Réunion"]&COHORT=["2020"]&APPLICATION_STATUS=["WAITING_VALIDATION"]](https://admin.snu.gouv.fr/volontaire?DEPARTMENT=%5B%22La+R%C3%A9union%22%5D&COHORT=%5B%222020%22%5D&APPLICATION_STATUS=%5B%22WAITING_VALIDATION%22%5D)

Parmi les 10 , 6 volontaires ont en réalité aucune candidature en attente de validation . Pourquoi ?

**Comment by lucienklein** [comment]
Il n'y a pas de problème mais je pense qu'il y a une mauvaise compréhension du user
