### ISSUE TITLE
feat(admin): classer les onglets de la sidebar

### ISSUE THREAD

**Issue by tangimds** [betagouv/service-national-universel#1161]
### Fonctionnalité

ranger les différents onglets du drawer par phase
- phase 0
- phase 1
- phase 2
- phase 3
- autres

**Comment by dimitri-bourreau** [comment]
J'aimerais aider, il y a-t-il des idenfiants de test pour se connecter à l'espace administrateur ?

**Comment by rap2hpoutre** [comment]
Bonjour @dimitri-bourreau et merci beaucoup pour ta proposition et ta motivation 🙏 
Bien qu'open-source, l'appli du Service National Universel n'est pour l'instant malheureusement pas prête à accueillir des contributeur et c'est complètement notre faute : il n'existe pas de moyen simple de démarrer le projet en local, tout est encore basé sur des échanges oraux entre les acteurs 😱, les modalités de contributions sont encore très floues.
On sera ravi de t'onboarder mais c'est encore un peu tôt pour nous, on n'est pas prêts. Ton message permet de mettre en lumière ce problème, du coup je t'en remercie, il faut qu'on planche là dessus !
À bientôt !

**Comment by dimitri-bourreau** [comment]
Bonjour @rap2hpoutre. 🙂

C'est ce que je craignais, et je comprends. 👍

J'ai l'intention d'orbiter autour de betagouv, j'aurais peut-être l'occasion de t'y croiser, et dans tous les cas merci pour ta réponse. 😊

**Comment by tangimds** [comment]
attente design
