### ISSUE TITLE
feat(admin): Chef de centre : pointage et validation

### ISSUE THREAD

**Issue by tangimds** [betagouv/service-national-universel#1228]
### Fonctionnalité liée à un problème ?

- Pendant le séjour, les chefs de centre vont pointer les volontaires (absent/présent), ce qui impactera leur validation au séjour de cohésion
- Ils devront également pointer la réception des fiches sanitaires

**Problème rencontré**

- Actuellement, les boutons sont figés (pas d’action possible) - côté chef de centre

### Fonctionnalité

Ouvrir au chef de centre la possibilité de pointer la présence des volontaires 
Désactiver la validation automatique de la phase 1 dès lors que le volontaire est indiqué comme présent (jusqu’au 21 février)

Ouvrir au chef de centre la possibilité de pointer la réception des fiches sanitaires

Lorsque la présence du volontaire est validé au 1er jour par le chef de centre ⇒ envoi d’un mail automatique aux représentants légaux du volontaire (Template SIB :  )

**Comment by lucienklein** [comment]
- [ ] Lorsque la présence du volontaire est validé au 1er jour par le chef de centre ⇒ envoi d’un mail automatique aux représentants légaux du volontaire (Template SIB : )
