### ISSUE TITLE
fix: Suppression structure par un référent

### ISSUE THREAD

**Issue by tangimds** [betagouv/service-national-universel#1616]
### Fonctionnalité liée à un problème ?

**Contexte**

- En tant que référent départemental et régional , je souhaite supprimer une structure qui n’a pas encore de candidatures
- ticket lié (pour la suppression d’un responsable de structure) : [[Suppression responsable de structure](https://www.notion.so/Suppression-responsable-de-structure-3d45f008544c4a6281a105bfe1329658)](https://www.notion.so/Suppression-responsable-de-structure-3d45f008544c4a6281a105bfe1329658))

**Problème rencontré**

- Un référent départemental et régional ne peut pas supprimer une structure

### Fonctionnalité

Permettre la suppression d’une structure sans candidatures sur ces missions aux référents régionaux et départementaux

### ticket

https://www.notion.so/jeveuxaider/Suppression-structure-par-un-r-f-rent-50e714e75a414aaf9c736267dc284d66

**Comment by pierre-lebihan** [comment]
https://github.com/betagouv/service-national-universel/pull/1619
