### ISSUE TITLE
refactor: formatDate

### ISSUE THREAD

**Issue by rap2hpoutre** [betagouv/service-national-universel#218]
There should be only one occurrence

<img width="285" alt="Capture d’écran 2021-06-07 à 15 00 03" src="https://user-images.githubusercontent.com/1575946/121020878-16bbca80-c7a1-11eb-88e3-b7a1bd5b9fe6.png">

**Comment by tangimds** [comment]
fix by https://github.com/betagouv/service-national-universel/pull/231
