### ISSUE TITLE
fix: footer position

### ISSUE THREAD

**Issue by rap2hpoutre** [betagouv/service-national-universel#225]
Le footer passe par dessus le menu, c'est inhabituel, il faudrait qu'il soit comme sur les sites normal :

<img width="889" alt="Capture d’écran 2021-06-08 à 16 02 38" src="https://user-images.githubusercontent.com/1575946/121199117-f4927d00-c872-11eb-9cec-b5aff140db90.png">

**Comment by johnSmith-png** [comment]
I can fix it but where is the footer file?

**Comment by rap2hpoutre** [comment]
IDK 😬 cc @tangimds ?

**Comment by johnSmith-png** [comment]
cc?
