### ISSUE TITLE
fix: edit structure

### ISSUE THREAD

**Issue by rap2hpoutre** [betagouv/service-national-universel#233]
L'édition d'une structure échoue sur un cas. A priori, un `label` sur `undefined`. Détail dans le ticket, il faut essayer de comprendre et corriger.

Trello: https://trello.com/c/Ghv3wz1A/657-admin-ecran-blanc-en-modifiant-le-texte-descriptif-dune-structure

**Comment by tangimds** [comment]
issue: l'asso avait un `assocationTypes === [' ']` (un array avec un element vide)
donc quand le composant `MultiSelect` bouclait sur cet attribut pour precocher les bonnes cases, il ne trouvait pas de `.label`.

fix : https://github.com/betagouv/service-national-universel/commit/ab940157c0e7e8bc928cf86b15a28ef2f4591d30
