### ISSUE TITLE
fix: dashboard on ie

### ISSUE THREAD

**Issue by rap2hpoutre** [betagouv/service-national-universel#238]
Trello: https://trello.com/c/EuKFjfq1/404-admin-tableau-de-bord-sur-ie

Si on y passe une heure sans avoir trouvé, on laisse une note dans le ticket et on abandonne.

**Comment by SpookyUmi** [comment]
Currently testing on Microsoft Edge, but there's no problem

**Comment by tangimds** [comment]
L'affichage est bugé sur Internet Explorer

**Comment by tangimds** [comment]
je close, je laisse un commentaire sur le trello.
