### ISSUE TITLE
feat(export): structure

### ISSUE THREAD

**Issue by rap2hpoutre** [betagouv/service-national-universel#240]
Ajouter membres de l'équipe (nom, prénom, adresse email, numéro de tel si renseigné)

<img width="1420" alt="Capture d’écran 2021-06-11 à 13 29 34" src="https://user-images.githubusercontent.com/1575946/121679849-18df9b00-cab9-11eb-9aff-616d1979db0b.png">

Trello: https://trello.com/c/VJwzkaWj/559-admin-enrichir-export-structure

**Comment by SpookyUmi** [comment]
There's no further informations about the structure's members, neither in the structure model nor in the object data we export

**Comment by tangimds** [comment]
What about it ?
