### ISSUE TITLE
chore(security): add helmet on app

### ISSUE THREAD

**Issue by rap2hpoutre** [betagouv/service-national-universel#244]
... et vérifier que ça marche toujours. Cf: https://github.com/betagouv/service-national-universel/blob/0a96b1f7c04c84de8946ffed610f1dfc57a914af/api/src/index.js#L8 et https://github.com/betagouv/service-national-universel/blob/0a96b1f7c04c84de8946ffed610f1dfc57a914af/api/src/index.js#L17

ça nous aidera à améliorer notre score ici : https://dashlord.incubateur.net/#/url/https://inscription.snu.gouv.fr

**Comment by SpookyUmi** [comment]
I'm sorry, need more insight on what to do here :/  @rap2hpoutre

**Comment by rap2hpoutre** [comment]
Let me know when we can tackle this!
