### ISSUE TITLE
feat: download contract (finish tangi PR)

### ISSUE THREAD

**Issue by rap2hpoutre** [betagouv/service-national-universel#256]
Trello : https://trello.com/c/CL7pqvs7/677-admin-contrat-dengagement

@tangimds a déjà commencé une PR ici : https://github.com/betagouv/service-national-universel/pull/253

Il manque "juste" à finaliser l'affichage 😇. Dans le cas de cet export c'est dupliqué, mais on va considérer que c'est OK 🙃 car ce n'est pas la même chose : c'est l'export VS l'autre fois c'était deux fois la même page d'édition.

**Comment by tangimds** [comment]
C'est du pur html-css (pas de styled component, pas de conditioned rendering, etc...) Si tu as besoin d'aide @hugo3m ping moi !
