### ISSUE TITLE
feat: improve responsive for app

### ISSUE THREAD

**Issue by rap2hpoutre** [betagouv/service-national-universel#259]
Cette tâche n'a pas vraiment de périmètre défini, il faut améliorer le responsive de l'app car la plupart des jeunes l'utilisent sur mobile (source ci dessous) et on sait qu'on peut mieux faire. Donc considérons qu'on met une limite de temps : 2 jours pas plus. Idéalement une PR par petite amélioration c'est plus simple pour livrer au fur et à mesure.

<img width="1286" alt="Capture d’écran 2021-06-15 à 11 12 02" src="https://user-images.githubusercontent.com/1575946/122026463-8564dd80-cdca-11eb-9abc-b3ba5e88ca46.png">

https://lumiere.cleverapps.io/apps/snu/dashboard

**Comment by tangimds** [comment]
Liste des améliorations possibles dans l'ordre des priorités :
- [x] améliorer la page d'accueil https://prnt.sc/15hfrf9
- [x] vue d'une mission (assze touchy, beaucoup d'infos, on peut en parler ! ) https://i.gyazo.com/726b83ed5574d16aea0b71d76e38bbdb.png
- [x] mettre en colonnes les infos pour une candidatures (infos contrats et infos tuteur) https://gyazo.com/04b1e76ca89d206a5921506acc5c167c
- [ ] mise en page des infos / bouton de la fiche sanitaire (`/phase1` en `affecté`) https://prnt.sc/15hfwsv
- [x] footer ? reduire la taille ? mise en page ? https://prnt.sc/15hg0ys

surement des écrans de phase 3, mais ceux ci dessus sont plus important aujourdhui

**Comment by tangimds** [comment]
J'ai fait quelques améliorations, je ferme cette issue.
On en ouvrira une autre si besoin
