### ISSUE TITLE
fix(cookie): investigation about session duration

### ISSUE THREAD

**Issue by rap2hpoutre** [betagouv/service-national-universel#264]
Nos sessions semblent cassées : elles ne semblent pas durer deux heures et quand on essaye d'augmenter le temps ça ne semble pas pris en compte. Il faudrait : 
- vérifier si ce que je dis est vrai
- se documenter sur la durée des cookie et comment les faire mieux marcher
- Idéalement arriver à les mettre pour 7 jours par défaut par exemple, ça ferait moins de galères pour tout le monde

https://github.com/betagouv/service-national-universel/blob/bd6446f6d104cd1778d43af6fb8d78b334b589f3/api/src/cookie-options.js#L3-L5

**Comment by hugo3m** [comment]
- La durée du cookie JSON fonctionne bien. Si on réduit cette durée alors la session est plus courte et on est redirigé. Ce cookie est stockée dans l'objet "API" du front-end. Pour l'instant ce token n'est pas supprimé à la déconnexion. Il est par contre remplacé par un nouveau token lors d'une nouvelle connexion. 
- Un second token est stockée dans les cookies. Ce token est vérifié si le front n'envoie pas de token lors d'une requête. Ce token est set et delete à chaque connexion/déconnexion.

J'ai encore du mal à comprendre l'intérêt d'avoir deux tokens stockés à deux endroits différents. J'essaye de continuer à comprendre comment le token est stocké dans le cookie et si la durée fonctionne bien. Je sais que si on réduit la durée du token JWT on est deconnecté car il dépasse son "âge" mais cela ne fonctionne pas si on réduit la durée du token des cookies.
