### ISSUE TITLE
Elastic Search search problem

### ISSUE THREAD

**Issue by hugo3m** [betagouv/service-national-universel#274]
- Les recherches elastic search ne sont pas try/catch = gros problème.
- Ces erreurs viennent du fait qu'il y a bcp trop de requêtes faites à un instant t levant une net::ERR_INSUFFICIENT_RESOURCES
- Sans try/catch l'application crash
![Screenshot 2021-06-17 at 3 29 15 PM](https://user-images.githubusercontent.com/58819009/122407654-13cf8f80-cf82-11eb-8f0d-cb85e0dd53a0.png)

**Comment by rap2hpoutre** [comment]
A priori c'est chome tout seul qui la balance l'erreur... https://stackoverflow.com/questions/24122506/neterr-insufficient-resources-error-when-adding-numerous-img-elements-to-dom

**Comment by rap2hpoutre** [comment]
ça met en avant aussi le problème qu'une requête est faite par ligne de structure pour calculer le nombre de places.
