### ISSUE TITLE
refactor: formatDateFR

### ISSUE THREAD

**Issue by rap2hpoutre** [betagouv/service-national-universel#275]
Il faut utiliser celui de lib (un coup `formatDateFR` et pour l'autre `formatStringDate`)

<img width="305" alt="Capture d’écran 2021-06-17 à 16 20 26" src="https://user-images.githubusercontent.com/1575946/122415161-f7ceec80-cf87-11eb-9f07-4ee8ca152a46.png">

**Comment by hugo3m** [comment]
On voulait installer la librairie dans l'API mais on peut pas car c'est pas la même syntaxe entre NodeJS et React?
![Screenshot 2021-06-17 at 6 08 38 PM](https://user-images.githubusercontent.com/58819009/122434054-0d97de00-cf97-11eb-9941-07d94a000c8e.png)
