### ISSUE TITLE
refactor: userless department and region list

### ISSUE THREAD

**Issue by rap2hpoutre** [betagouv/service-national-universel#276]
Ces lignes : https://github.com/betagouv/service-national-universel/blob/412f1c09cf3b0e37a0809ca644cedb27c0725619/api/src/crons/utils.js#L35-L142 et celles là : https://github.com/betagouv/service-national-universel/blob/412f1c09cf3b0e37a0809ca644cedb27c0725619/api/src/crons/utils.js#L145-L171

peuvent être remplacées par `departmentList` et `regionList` de `https://github.com/betagouv/service-national-universel/blob/main/lib/region-and-departments.js`: https://github.com/betagouv/service-national-universel/blob/412f1c09cf3b0e37a0809ca644cedb27c0725619/lib/region-and-departments.js#L110 et https://github.com/betagouv/service-national-universel/blob/412f1c09cf3b0e37a0809ca644cedb27c0725619/lib/region-and-departments.js#L114

**Comment by hugo3m** [comment]
problème d'import de la lib dans le backend
