### ISSUE TITLE
Fix(Mission) : Mission non visible sur l'app

### ISSUE THREAD

**Issue by tangimds** [betagouv/service-national-universel#284]
Certaines missions n'apparaissent pas côté jeune. `/mission`

Une mission validée, qui est dans le périmètre définie dans les filtres doit apparaitre pour le jeune.
Le problème vient surement de mission sans localisation GPS.

**Comment by hugo3m** [comment]
- Des jeunes n'ont pas de localisation car ils ont rentré leur adresse manuellement 
- Des missions n'ont pas de localisation car les adresses sont rentrées manuellement
=> Conséquence : des jeunes ne trouvent pas de missions car ils n'ont pas de localisation OU les missions n'ont pas de localisation
Solution : Pas besoin d'avoir une localisation exacte. Une localisation avec le ZIP Code suffit. Obligé tous les jeunes et missions à avoir une ZIP Code et leur attribuer une localisation en fonction de ce ZIP Code + Faire tourner un script pour combler les manques en cherchant la localisation avec le ZIP Code.

**Comment by hugo3m** [comment]
après reflexion : un ZIP Code c'est pas assez car les communautés de communes peuvent être grandes. Un nom de ville n'est pas non plus suffisant car certaines villes dans différentes régions ont le même nom.
 Conclusion : Obliger un ZIP Code + Un nom de ville minimum et rechercher la latitude et longitude au POST
