### ISSUE TITLE
refactor: remove api calls in Hits

### ISSUE THREAD

**Issue by tangimds** [betagouv/service-national-universel#294]
Enlever tout les appels api/es dans les `Hit` au sein d'une liste.
Il faudra privilégier la méthode mise en place par Raph dans l'onglet structure.
=> si il faut faire des call dans les hits, on fait un seul call au début pour récuperer toutes les infos nécessaire, et chaque hit filtrera sur ses propres données

**Comment by rap2hpoutre** [comment]
See: https://github.com/betagouv/service-national-universel/commit/cdd8300039132d521d1c47e2b096de245580966f
