### ISSUE TITLE
feat: templates sendinblue

### ISSUE THREAD

**Issue by tangimds** [betagouv/service-national-universel#369]
[tableau excel](https://docs.google.com/spreadsheets/d/1y_HI07B42PmhKLp513pU00STTRaehguQaa9jxj6iJIs/edit#gid=2026044365) tab Notifications 2021
Pour toutes les notifs qui partent de la plateforme, utiliser les templates sendinblue.

- [x] mail fonctionnement général
  - [x] mot de passe oublié

### jeune
- [x] mail phase d'inscription
  - [x] inscription validée
  - [x] correction
  - [x] refusée
  - [x] liste d'attente
- [ ] mail phase 1
  - [ ] ?
- [ ] mail phase 2
  - [x] preparation militaire
    - [x] docs validé
    - [x] docs correction
    - [x] docs refusé
  - [x] accepté a une mission
  - [x] refusé a une mission
  - [x] proposer une mission
- [ ] mail phase 3
  - [ ] ?

### admin
- [ ] mail phase d'inscription
  - [x] nouvelle inscription
- [ ] mail phase 1
  - [ ] ?
- [ ] mail phase 2
  - [ ] preparation militaire
    - [x] docs deposé
    - [x] docs validé
  - [x] candidarue a une mission
  - [x] candidature annulée par le jeune
- [ ] mail phase 3
  - [x] valider mission phase 3

**Comment by rap2hpoutre** [comment]
Est-ce que cette adresse existe déjà ? Je crois qu'il faut qu'une adresse existe pour que ça n'arrive pas dans les spams.

A priori non: 

> Réponse du serveur distant :
550 5.1.1 <noreply@snu.gouv.fr>: Recipient address rejected: Address does not exist

**Comment by tangimds** [comment]
ah yes effectivement, je pensais qu'elle etait deja utilisée sur les campagnes. Faudrait voir avec Noémie
