### ISSUE TITLE
fix : contract : infos representants légaux manquantes

### ISSUE THREAD

**Issue by tangimds** [betagouv/service-national-universel#380]
Est-ce normal/souhaité ou non, que la rubrique présentant les infos des représentants légaux qui s'affichent lorsque le contrat est signé et téléchargeable , ne s'affiche pas avant la génération du contrat d'engagement , depuis l'espace de la structure ?  

https://trello.com/c/3bLzwoAi

**Comment by hugo3m** [comment]
Manifestement l'issue est vieille et cette feature a été rajouté/fixe depuis

**Comment by hugo3m** [comment]
à supprimer
