### ISSUE TITLE
fix : filter response object

### ISSUE THREAD

**Issue by tangimds** [betagouv/service-national-universel#394]
Maitriser ce qu'on renvoie de l'api. Pour l'instant, on renvoie souvent tout l'objet.
Ce n'est pas bon du tout.

Une premiere étape serait de mettre en place des `scope` en fonction du role de l'utilisateur.
- Un jeune peut avoir accès a ces propres tokens, pas les référents

**Comment by rap2hpoutre** [comment]
J'aimais bien l'approche transformers/fractal en PHP : https://fractal.thephpleague.com/transformers/ (et pour laravel : https://github.com/spatie/laravel-fractal)

**Comment by rap2hpoutre** [comment]
On a choisi ça : https://github.com/betagouv/service-national-universel/blob/main/api/src/utils/serializer.js
