### ISSUE TITLE
fix: remove "… déjà inscrits"

### ISSUE THREAD

**Issue by rap2hpoutre** [betagouv/service-national-universel#431]
<img width="1141" alt="Capture d’écran 2021-08-23 à 15 06 54" src="https://user-images.githubusercontent.com/1575946/130452527-6d854b3e-c711-4e20-b851-a9e4844fb730.png">

Parce que ça ne sert à rien.

**Comment by tangimds** [comment]
A voir, mais les objectifs sont peut etre meme à enlever completement (car incomplets et un peu abandonnés)
