### ISSUE TITLE
fix: find alternative when navigator.clipboard is undefined

### ISSUE THREAD

**Issue by rap2hpoutre** [betagouv/service-national-universel#432]
`navigator.clipboard`

<img width="412" alt="Capture d’écran 2021-08-23 à 16 08 18" src="https://user-images.githubusercontent.com/1575946/130461694-30a50305-81d2-4fa5-9b47-548c9c23dc11.png">

More info: https://stackoverflow.com/questions/51805395/navigator-clipboard-is-undefined

**Comment by hugo3m** [comment]
Pour le clipboard je peux essayer de faire comme dit ici https://stackoverflow.com/questions/51805395/navigator-clipboard-is-undefined et dire que si navigator.clipboard undefined alors je fais de l’autre manière avec le textArea. Chez moi ça fonctionne après ça résout le problème de copier-coller mais pas pourquoi le copier-coller fonctionne pas
