### ISSUE TITLE
feat: do not send mail to PM manager

### ISSUE THREAD

**Issue by rap2hpoutre** [betagouv/service-national-universel#445]
Extrait de discussion : https://servicenation-hed2328.slack.com/archives/G01J0C7BTR9/p1630398547009000

Un responsable de structure militaire vient de me faire remonter qu'il recevait 2 type de mails :
1er : dès qu'un volontaire candidate
2è : lorsque le référent valide les pièces et qu'il peut accéder à la candidature.
Pensez-vous que le 1er est nécessaire ?

...

Effectivement le premier est pas nécessaire

...

utils dans admin
il y a une fonction qui, pour un user donné, dit si il fait parti d’une structure PM

**Comment by hugo3m** [comment]
1 - Le jeune crée sa candidature :
 le référent départemental, le référent régional ou le manager de département (dans cet ordre) est notifié
et non pas le tuteur de mission pour les PM.
	2 - Le jeune dépose ses documents : le référent départemental, le référent régional ou le manager de département (dans cet ordre) est notifié
	3 - Les documents sont validés par le réfèrent de l’étape 2 : Le jeune est notifié ET tous les tuteurs de missions sur les missions militaires sur lesquelles le jeune a candidaté sont notifiés
