### ISSUE TITLE
feat: add phase2ValidationDate for young

### ISSUE THREAD

**Issue by rap2hpoutre** [betagouv/service-national-universel#494]
Il faut ajouter une propriété au modèle Young : `phase2ValidationDate` (ou un autre nom plus cohérent avec le reste, à checker) qui contient une date qui est mise à jour à chaque fois que le statut de phase 2 d'un jeune passe à "Effectuée".

Cela permettra ensuite d'utiliser la VRAIE date (et non pas la date du jour) quand elle est présente dans l'attestation de fin de phase 2 :

<img width="1078" alt="Capture d’écran 2021-10-07 à 16 48 04" src="https://user-images.githubusercontent.com/1575946/136408819-c169822f-f62b-4d7b-a380-0d22b6a45c23.png">

Autrement dit dans l'ordre : 
- Ajouter le champ au modèle
- Vérifier dans les controllers, pour que partout ou le statut de phase 2 est mis à jour mettre la date au moment où on enregistre (on met toujours la dernière date, même si le statut à changé plusieurs fois)
- Mettre à jour le certificat en prenant cette date, et à défaut la date du jour pour les comptes où ce n'est pas renseigné

Source : https://trello.com/c/pcawO2Bt/823-admin-app-figer-la-date-fait-le-de-lattestation-phase-2-%C3%A0-la-date-de-validation-de-la-phase-2-sur-la-plateforme

**Comment by tangimds** [comment]
cf #477
