### ISSUE TITLE
fix: trim (left and right) before search

### ISSUE THREAD

**Issue by rap2hpoutre** [betagouv/service-national-universel#497]
Une recherche avec des espaces avant ou après (c'est le cas en cas de copier coller) échoue. Il faudrait que ça n'ait pas d'impact (attention, on ne change pas l'input de l'utilisateur, rien de pire que de se faire effacer / rajouter des caractères par erreur)

<img width="823" alt="Capture d’écran 2021-10-08 à 09 19 35" src="https://user-images.githubusercontent.com/1575946/136514578-2073588c-d8ac-4227-8413-3b81e1f44675.png">

**Comment by tangimds** [comment]
j'ai l'impression que ce n'est le cas que pour les mails ? @lucienklein
