### ISSUE TITLE
fix(search): search mendes or mendès should return mendès and mendes

### ISSUE THREAD

**Issue by rap2hpoutre** [betagouv/service-national-universel#498]
Actuellement si je cherche "mendès" j'ai seulement "mendès". Si je cherche "mendes" j'ai seulement "mendes". C'est un vrai problème pour les recherches sur les jeunes, particulièrement sur les noms de famille. Elasticsearch permet normalement de faire des meilleures recherche.

Cette tâche doit être timeboxée à 2h et si c'est réussi tant mieux, sinon mettre un petit rapport de ce qui n'a pas marché ici, pour pas qu'on reparte de zéro. Bon courage 😄

**Comment by lucienklein** [comment]
Il faut ajouter un token dans les settings: [Doc Elastic : ASCII Folding Token Filter](https://www.elastic.co/guide/en/elasticsearch/reference/6.3/analysis-asciifolding-tokenfilter.html)
@rap2hpoutre je te laisse reprendre l'issue
