### ISSUE TITLE
feat: more info for structure

### ISSUE THREAD

**Issue by rap2hpoutre** [betagouv/service-national-universel#509]
Source : https://trello.com/c/pkpagXNg/904-admin-am%C3%A9liorer-le-volet-de-droite-structure

> - liste des 10 premières missions (nom + lien)
> - bouton :voir plus si + de 10

Suite de https://github.com/betagouv/service-national-universel/issues/473

**Comment by lucienklein** [comment]
@rap2hpoutre c'est la même que la #503 non ?
