### ISSUE TITLE
fix: couleur bouton violet

### ISSUE THREAD

**Issue by tangimds** [betagouv/service-national-universel#534]
### Description du bug

Le bouton est censé etre violet, mais parfois s'affiche en gris (apres refresh, repasse en violet)

### Comment le reproduire ?

je ne sais pas ce qui provoque ce comportement :/
il faut enquêter directement sur le component du bouton

(ce bug arrive parfois sur la page du login, donc ce n'est pas lié spécifiaquement a la page)

### Comportement attendu

il faut qu'il soit violet tout le temps, sauf si explicitement `disabled`
Je pense que le probleme vient du state et/ou des regles css qui se chevauchent...

### Une image vaut 1000 mots

https://prnt.sc/1vtvgui

**Comment by lucienklein** [comment]
J’ai pas réussie à refaire le bug @tangimds

**Comment by tangimds** [comment]
moi non plus, c'est ce que je mettais dans le ticket, mais je pense qu'il faudrait améliorer le composant bouton...
mais effectivement, sans savoir d'ou vient le bug, il est compliqué de savoir si on la fix.
Je veux bien que tu passes ~20-30 minutes a voir le composant, voir pourquoi il pourrait etre gris dans certains cas. et peut etre proposer des refacto qui ne changent pas le comportement actuel. (peut etre qu'en faisant un composant plus robuste, on eliminera le bug mystère)

**Comment by tangimds** [comment]
https://prnt.sc/1vym9yq

**Comment by tangimds** [comment]
merged
