### ISSUE TITLE
fix(inbox): redux tickets - step 1 badges

### ISSUE THREAD

**Issue by tangimds** [betagouv/service-national-universel#594]
### Fonctionnalité liée à un problème ?

on a un nombre de notif dans le drawer et quand on clique sur l'onglet on arrive sur ca -> https://prnt.sc/1wy2tp6

### Fonctionnalité

il faudrait que le header avec les stats utilisent le redux aussi
On peut commencer par une premiere etape ou on branche jsute les notifs, on pourra voir par la suite pour brancher les tickets aussi

arriver sur l'onglet boite de reception avec les tickets deja chargés ce serait sexy

### Commentaires

https://prnt.sc/1wy2tp6

**Comment by SpookyUmi** [comment]
Yes, j'attendais de voir si c'était bien fonctionnel pour utiliser le reducer un peu partout :)
