### ISSUE TITLE
fix(inscription): front inscription form

### ISSUE THREAD

**Issue by tangimds** [betagouv/service-national-universel#620]
### Fonctionnalité liée à un problème ?

L'idée est de reproduire le figma sur notre formulaire existant

### Fonctionnalité

lien du figma 👉 [ici](https://www.figma.com/file/YrtsZrwl3mBlVNMr26xElB/SNU-2021%2F2022-(Copy)?node-id=0%3A1)

*editer la ligne en indiquant si vous trouvaillez sur un ecran*
- [x] landing page
- [x] step 1 - profil
- [x] step 2 - coordonnées
- [x] step 3 - situations particulieres
- [x] step 4 - representants legaux
- [x] step 5 - consentements
- [x] step 6 - pieces justificatives
- [ ] disponiblités

**Comment by lucienklein** [comment]
Il y a déjà une PR #621 pour le step 1

**Comment by lucienklein** [comment]
@SpookyUmi fait le step 2

**Comment by lucienklein** [comment]
Je fais le step 3

**Comment by lucienklein** [comment]
PR #622 ouverte pour le step 3. Attention, c'est un draft, il y a encore des trucs en attente par rapport au Figma

**Comment by lucienklein** [comment]
Je fais le step 4

**Comment by lucienklein** [comment]
PR #626 ouverte pour le step 4

**Comment by lucienklein** [comment]
Je fais le step 5

**Comment by lucienklein** [comment]
PR #628 ouverte pour le step 5

**Comment by lucienklein** [comment]
Je fais le step 6

**Comment by lucienklein** [comment]
PR #629 ouverte pour le step 6

**Comment by tangimds** [comment]
merci @lucienklein !
