### ISSUE TITLE
fix(inbox): message isn't sent

### ISSUE THREAD

**Issue by SpookyUmi** [betagouv/service-national-universel#636]
### Description du bug

When an admin or referent try to respond to a message, an error occurs (400 bad request and Unauthorized).

### Comportement attendu

We should be able to send messages

**Comment by tangimds** [comment]
@SpookyUmi c'est corrigé ca ? ou c'est lié au message de Bertille dans Slack
> On reçoit de plus en plus de mails suite à nos réponses au formulaire de contact (externe) exemple ci-dessous. On ne recevait pas ces mails avant quand on était sur proton https://files.slack.com/files-pri/T01CUVC1R7D-F02MVMCBVCJ/image.png

**Comment by tangimds** [comment]
stand by, on reouvre si besoin
