### ISSUE TITLE
feat: maj le modele pour gerer les sous cohortes

### ISSUE THREAD

**Issue by tangimds** [betagouv/service-national-universel#645]
### Fonctionnalité

ajouter un champs dans le model `young` pour ajouter une granularité supplémentaire (identification de cohorte)

**Comment by rap2hpoutre** [comment]
Done via https://trello.com/c/yOlecgOD/942-admin-pr%C3%A9parer-cohortes-2022-dans-tableaux-de-bord-et-onglets
