### ISSUE TITLE
fix: Cannot read properties of null (reading 'firstName')

### ISSUE THREAD

**Issue by tangimds** [betagouv/service-national-universel#655]
### Description du bug

https://sentry.io/organizations/selego/issues/2763027021/?project=5557988&referrer=slack

le `referentManagerPhase2` n'est pas trouvé pour un jeune : https://github.com/betagouv/service-national-universel/blob/9f7329bbf39fb7358858cb8027c595308cd64105/api/src/controllers/application.js#L208

**Comment by lucienklein** [comment]
Mise en attente

**Comment by tangimds** [comment]
je close, on reouvre si besoin
