### ISSUE TITLE
fix: sous onglet par cohortes - centre de cohésion

### ISSUE THREAD

**Issue by tangimds** [betagouv/service-national-universel#690]
### Fonctionnalité

faire comme pour les objectifs, ajouter un filtre a l'écran actuel pour filtrer par cohorte

il est possible qu'il faille modifier le model des centres de cohésions pour rajouter la cohorte. (les existants serait a mettre a la cohore 2021

**Comment by rap2hpoutre** [comment]
@tangimds C'est le 4eme point de ce ticket ? https://trello.com/c/yOlecgOD/942-admin-pr%C3%A9parer-cohortes-2022-dans-tableaux-de-bord-et-onglets

Note : si oui, deadline 1/12

**Comment by tangimds** [comment]
on attend

**Comment by tangimds** [comment]
ticket en double.
on le fait en plusiseurs etape
voici la premiere etape : #951
