### ISSUE TITLE
fix: Affichage établissement

### ISSUE THREAD

**Issue by tangimds** [betagouv/service-national-universel#929]
### Fonctionnalité liée à un problème ?

Le module de recherche ne trouve par le Lycée Alfred Kastler (ligne 23190) du fichier des établissements

La ville de Cergy pontoise n'est reconnue que sous le nom de : Cergy OU pontoise

### Fonctionnalité

a enqueter, le component a pas mal évolué, c'est peut etre corrigé partiellement depuis

**Comment by lucienklein** [comment]
Même problème que l'issue #826 ?

**Comment by tangimds** [comment]
corrigé en partie, on reste vigilant si d'autres pb similaires sont remontent au support
